---
# These task run docker-compose build

- name: Echo git pull result
  debug:
   msg: 'git pull result: "{{ git_pull_result.stdout }}"'
   
- name: Run Console build
  shell: chdir=/home/nailit docker-compose up --build -d
  when: git_pull_result.stdout.find('Already up-to-date') == -1
  register: build_console_result

- name: Run Instasite build
  shell: chdir=/home/nailit docker-compose -f docker-compose.insta.yml up --build -d
  when: build_console_result is changed
  register: build_insta_result
